Rails:
  Enabled: true

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'

Metrics/LineLength:
  Max: 99

Metrics/CyclomaticComplexity:
  Severity: warning