language: ruby
sudo: false

cache:
  bundler: true
  directories:
    - /tmp/cache/unicode_conformance
    - /tmp/beanstalkd-1.10

services:
  - memcached
  - redis
  - rabbitmq

bundler_args: --without test --jobs 3 --retry 3

before_install:
  - rvm @global do gem uninstall bundler --all --ignore-dependencies --executables
  - rvm @global do gem install bundler -v '1.11.2'
  - bundle --version
  - "rm ${BUNDLE_GEMFILE}.lock"

before_script:
  - bundle update

script: 'ci/travis.rb'


rvm:
  - 2.3.1
  - ruby-head

env:
  - DB=sqlite
  #- DB=mysql
script:
  - rake db:migrate
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare




